CREATE USER IF NOT EXISTS 'andyortegak'@'%' IDENTIFIED BY 'kou12345';
GRANT ALL PRIVILEGES ON blog_db.* TO 'andyortegak'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS blog_db;

CREATE TABLE IF NOT EXISTS blog_posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    pokemon_name VARCHAR(255) NOT NULL,
    tipo_pokemon VARCHAR(255) NOT NULL,
    grupo VARCHAR(255) NOT NULL,
    cualidad VARCHAR(255) NOT NULL,
    region VARCHAR(255) NOT NULL,
    descripcion VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(255) NOT NULL,
    contrasena VARCHAR(255) NOT NULL
);